### ISSUE TITLE
Hitting lots of errors from lib folder

### ISSUE THREAD

**Issue by BeyoncesHomeboy** [markusressel/py-image-dedup#11]
everytime I run the image dedup it hits an error but they all seems to becoming from... ..\python\python36\lib\[some package]
some examples are:
python\python36\lib\site-packages\urllib3\util\retry.py
python\python36\lib\http\client.py
python\python36\lib\site-packages\urllib3\connectionpool.py
...

idk if you I need to copy and paste the massive errors that are occurring but idk what to do anymore. Either from deleting everything in the lib folder or what to do anymore.

**Comment by markusressel** [comment]
I would like to help you but I have no clue what error you are getting and where.
It sounds like you have db connection issues so I guess you didn't setup the config correctly or have no elasticsearch database running.

Just pase the error log here using backticks, it will have a scrollbar automatically if the content is to long. F.ex.:

``````
```
this is a long error message
with multiple lines
```
``````
