### ISSUE TITLE
container_app_conf

### ISSUE THREAD

**Issue by byagiz** [markusressel/py-image-dedup#231]
Running the example.py results in the following error:
ModuleNotFoundError: No module named 'container_app_conf

To replicate the error:
create a python environment
install py-image-dedup via pip install py-image-dedup
python3 example.py

Any idea why this could happen? pip list shows py-imaged-dedup as installed but the installation gave some error messages. I can post them here if needed

**Comment by markusressel** [comment]
Closing in favor of #97
