### ISSUE TITLE
Simplified usage with Docker

### ISSUE THREAD

**Issue by qdrop17** [markusressel/py-image-dedup#4]
Hi there.

This is more kind of a feature request then it is an issue. It would be great to have that entire solution in a self-contained Docker image. Both DB and application. This would make the usage far easier.

For instance one could directly use it on Synology-NASes.

Thanks for considering. If I have time, I might try to setup something myself.

**Comment by markusressel** [comment]
Sure thing this would be nice to have. If you get around it open a PR and I will gladly merge it :blush:

**Comment by qdrop17** [comment]
Actually, I don't even get it running natively. Would it be possible if you create some "how to use" with couple of commands and instructions on how to install and use your software?

That would be great.

Unfortunately I don't have a lot of python experience so far. But I would like to use your software as it's really doing what I need on my NAS...

**Comment by markusressel** [comment]
Yeah I'm sorry it's so difficult to set up. Part of that is also due to image-match beeing outdated. I will try to getto this on the weekend. Glad you like it! :)

**Comment by markusressel** [comment]
Hey, just a little heads up:
I worked the whole day on #5 which will hopefully make it a lot easier to run py-image-dedup inside a container. While doing this I also had some issues with the latest version of elasticsearch that I had installed locally on my dev machine. I have fixed these issues now, so you can give it another shot if you use a recent version of elasticsearch too.

**Comment by markusressel** [comment]
@qdrop17 fyi, I have finished docker support. I still need to write some documentation for it in the README but if you understand how docker works and docker-compose have a look :nerd_face:

**Comment by qdrop17** [comment]
> @qdrop17 fyi, I have finished docker support. I still need to write some documentation for it in the README but if you understand how docker works and docker-compose have a look 🤓

Very cool, thank you so much! It actually works flawlessly on a generic Ubuntu machine. But it's not working on my DS718+ NAS. Maybe a broken Docker installation or incompatibilities with the CPU.

The py-image-dedup container is not writing any logs on this NAS.

Thank you very much for your efforts anyway!
