### ISSUE TITLE
File configuration

### ISSUE THREAD

**Issue by markusressel** [markusressel/py-image-dedup#5]
Since py-image-dedup has a lot of things to configure the amount of cli command parameters is pretty high. To make it easier to reuse and iterate on a run configuration it would be great to use a file configuration that is read on startup instead.

To implement this and also make it easy to use py-image-dedup in a container [container-app-conf](https://github.com/markusressel/container-app-conf) shall be used.

This will probably also make it easier to tun py-image-dedup as a service when #3 is implemented.

**Comment by qdrop17** [comment]
Awesome, I'm having a look at it next week :-)
