### ISSUE TITLE
Custom prioritization

### ISSUE THREAD

**Issue by markusressel** [markusressel/py-image-dedup#80]
**Is your feature request related to a problem? Please describe.**
The current prioritization of similar images is hardcoded into the library. A user might want to change this logic though, based on unique constrains of the dataset that is deduplicated.

**Describe the solution you'd like**
Allow the user to specify how similar images are ranked against each other.
One possibility would be to utilize the YAML config, however, the library used for the configuration is not really suited for a configuration that is so dynamic. A separate file that defines the ranking process would probably be a better idea.

Open questions:
- [ ] What does the file format look like?
- [ ] What does the user specify in this file?
- [ ] Should there be alternative ways of specifying the ranking behavior?

**Comment by TKaluza** [comment]
I totally agree that a config is the way to go. 

But maybe as a first step it could be sufficient to address one or two main cases with different prioritization that the users can choose per command. 

The original hard-coded criteria list fits finding new images copies, but for example finding the originals photos from a camera it might look like this:

1. EXIF data (more EXIF data is better)
2. EXIF Creation Date (lesser timedelta for EXIF creation date to file creation date is better)*
3. Pixel Dimension (if EXIF PIXEL dimension, then compare real pixel dimension to EXIF pixel dimension)
4. pixel count (more is better)
5. distance (lower is better)
6. filename contains "copy" (False is better)
7. file modification (older is better)
9. score (higher is better)

@markusressel What do you think?
