### ISSUE TITLE
Installing via setup.py does not use forked image-match version

### ISSUE THREAD

**Issue by stormriderDE** [markusressel/py-image-dedup#97]
**Describe the bug**
Image-Match dependency on 'elasticsearch<2.4,>=2.3'

**To Reproduce**
1. Clone Git
2. Setup virtual environment
3. Run python setup.py install
4. pkg_resources.ContextualVersionConflict: (elasticsearch 7.10.0 (/Users/michael/Documents/Python_Workspace/py-image-dedup/myenv/lib/python3.8/site-packages/elasticsearch-7.10.0-py3.8.egg), Requirement.parse('elasticsearch<2.4,>=2.3'), {'image-match'})

**Expected behavior**
Conflict with Elasticsearch 7.10.0 on py-image-dedup-end and elasticsearch<2.4,>=2.3 on image-match-end

**Screenshots**
![image](https://user-images.githubusercontent.com/75095358/100388601-543ddf00-302b-11eb-9ff8-be68cd78f886.png)

**Desktop (please complete the following information):**
 - OS: Mac OS

**Additional context**

**Comment by markusressel** [comment]
Not sure why you are getting this, but py-image-dedup does **not** use the official version of image-match, but a forked version, which supports more recent versions of elasticsearch. You cannot use the official version (which is seemingly not updated anymore anyway).

**Comment by stormriderDE** [comment]
Weird. I've deleted the virtual environment and installed everything from scratch again (via python setup.py install). Same result again (see screenshot below).

How can I fix this? Your help is very much appreciated!

![image](https://user-images.githubusercontent.com/75095358/100390694-966a1f00-3031-11eb-8929-8de54ca2077d.png)

**Comment by markusressel** [comment]
Hmm not sure, I guess you can directly use pipenv to install dependencies. Have a look at how it is done in the Dockerfile of this repo. It should be possible to use setup.py directly though, so I will keep this open.

**Comment by markusressel** [comment]
The project now uses Poetry, which should fix this issue.
Feel free to reopen if it doesn't.
